# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bjPJS3oGklhcnwvSoIN_993yGvSLSojZ
"""

import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,f1_score,classification_report
import pickle

# collect dataset
df = pd.read_csv(r"C:\Users\Akash\Desktop\Datasets\heartattack.csv")

print(list(df.columns))
print(df.isnull().sum())

x = df.drop("target",axis=1)
y = df["target"]

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2 , random_state=42)

# object of model

DC = DecisionTreeClassifier()

DC.fit(x_train,y_train)

pickle.dump(DC,open("DCmodels.pkl","wb"))

